// Auction XI has no cloud-save/login backend. Never reuse the other game's policies.
function auctionPages(config, { layout, escapeHtml, contactBlock }) {
  const root = '/products/auction-xi/';
  const email = escapeHtml(config.publisher.email);
  const contact = contactBlock(config);
  const link = (route, label) => `<a href="${root}${route}/">${label}</a>`;
  const heading = title => `<section class="hero"><p class="kicker">Sunlight · Auction XI</p><h1>${title}</h1><p class="effective">Effective 5 October 2026</p></section>`;
  const pages = {
    '': {
      title: 'Auction XI',
      description: 'Auction XI — fictional cricket club management, auctions, leagues and cups. Official policies and support from Sunlight.',
      body: `${heading('Auction XI')}<section class="product-overview"><div><p class="kicker">Android · In testing</p><h2>Build the club. Pick the XI. Chase the title.</h2><p>Manage a fictional cricket club through player auctions, squad selection, staff appointments, facilities, player development, leagues and cups.</p><p>Careers are saved locally on your device. Google sign-in and cloud saves are not available in the current version. Paid features depend on store availability; purchasing is never a guarantee of winning.</p></div><div class="product-icon-panel"><img class="app-icon" src="/auction-xi-icon.png" alt="Auction XI app icon" width="512" height="512"></div></section>
      <section class="section-intro"><h2>Legal &amp; support</h2><p>These pages apply only to Auction XI, not to other Sunlight apps.</p></section>
      <section class="link-grid">${[['privacy', 'Privacy Policy', 'Data, providers and your choices.'], ['terms', 'Terms of Use', 'Gameplay, purchases and consumer rights.'], ['support', 'Help & Support', 'Gameplay and purchase assistance.'], ['delete-data', 'Delete your data', 'Local saves and privacy requests.']].map(([route, title, detail]) => `<a class="link-card" href="${root}${route}/"><strong>${title}</strong><span>${detail}</span></a>`).join('')}</section>`,
    },
    privacy: {
      title: 'Auction XI Privacy Policy',
      description: 'How Sunlight handles information in Auction XI, including local saves, purchases, support and advertising where enabled.',
      body: `${heading('Auction XI Privacy Policy')}<article>
      <section><h2>Who we are and scope</h2><p>Sunlight provides Auction XI. Our legal operator is identified on our <a href="/publisher/">Publisher Information</a> page. This policy covers Auction XI and its related support and website pages; other Sunlight games have separate policies.</p>${contact}</section>
      <section><h2>Local gameplay and device storage</h2><p>Club and manager names you enter, careers, squads, match results, finances, preferences and local recovery copies are stored on your device. The current version does not upload career saves or offer Google sign-in, cloud saves or public leaderboards. Android device backup may retain app data according to your device and Google backup settings; it is not a Sunlight-operated cloud save service.</p><p>The app does not request access to your microphone, contacts, camera or precise location. Commentary uses prerecorded audio, not microphone recordings. We do not include Firebase Analytics or Crashlytics in this version.</p></section>
      <section><h2>Purchases and technical information</h2><p>Where purchasing services are configured, Google Play processes payments and RevenueCat manages purchase verification and permanent entitlements. RevenueCat uses a generated pseudonymous app-user identifier even without a Sunlight login. These services may process purchase history, product and transaction identifiers, entitlement and refund status, app/device information and network information such as IP addresses to operate, secure and troubleshoot purchases. Sunlight does not receive your full payment-card number. Purchase-service processing can occur when the configured app connects, not only when you buy.</p></section>
      <section><h2>Advertising, where enabled</h2><p>Advertising is disabled in the current testing configuration. In builds where ads are enabled, Google Mobile Ads and its consent service may process IP addresses (including approximate location), device/advertising identifiers, app and ad interactions, diagnostics and consent choices for ad delivery, measurement and fraud prevention. Non-personalized ads can still involve this processing. The app requests non-personalized inventory and waits until the consent service permits ad requests. Ad privacy options are available in Settings where supported. Buying Remove Ads does not erase earlier provider records.</p></section>
      <section><h2>Support and this website</h2><p>If you email us, we receive your email address, message and any attachments or order reference you choose to send. We use them to answer the request, investigate issues and handle purchase or privacy disputes. Please avoid sending passwords, payment-card details or unrelated personal information.</p><p>Cloudflare hosts these pages and may process IP addresses, request headers and security logs to deliver and protect the website. This static site has no advertising trackers, analytics scripts or contact-form database.</p></section>
      <section><h2>Providers and purposes</h2><p>We use information to run requested features, verify and restore purchases, prevent fraud, provide support, meet legal obligations and, where enabled and permitted, serve ads. Relevant providers include Google Play, RevenueCat, Google Mobile Ads, Cloudflare and the email provider handling support correspondence. They may process information outside your country under their own privacy notices and applicable safeguards. We may disclose information when legally required or necessary to protect users and services.</p><p>See <a href="https://policies.google.com/privacy">Google Privacy Policy</a>, <a href="https://www.revenuecat.com/privacy/">RevenueCat Privacy Policy</a> and <a href="https://www.cloudflare.com/privacypolicy/">Cloudflare Privacy Policy</a>. We do not sell your personal data.</p></section>
      <section><h2>Retention and deletion</h2><p>Local careers remain until you delete them or clear the app's data. Device backups are managed separately through Android/Google settings. Support correspondence is kept while needed to resolve the request and related disputes or legal obligations. Purchase records are retained while needed to provide entitlements, prevent duplicate grants and address refunds, fraud or legal requirements. Provider-controlled records follow the provider's retention rules; deleting a local save does not delete those records.</p><p>You can request review and deletion of information we hold using ${link('delete-data', 'our data-deletion instructions')}. We may request proportionate verification, and explain any records that must be retained and why. We do not promise deletion of records controlled independently by Google Play.</p></section>
      <section><h2>Your choices, rights and younger users</h2><p>You may contact us to request access, correction, deletion or a copy of your information, withdraw consent where processing relies on it, or raise a privacy concern. Applicable rights depend on your location and may include complaining to your local data-protection authority. Withdrawing consent does not invalidate earlier lawful processing.</p><p>Young users should use the app only with any permission required by local law; purchases require the payment account holder's authorization. We do not offer a verified parental-consent service. A parent or guardian concerned about information supplied by a child should contact us for review and deletion assistance. Advertising remains disabled while release audience settings are being finalized.</p></section>
      <section><h2>Security and changes</h2><p>We use restricted access and provider security measures; no device or service can guarantee absolute security. Protect your device and store account. We will update this page and its effective date when practices change and provide additional notice where required.</p></section></article>`,
    },
    terms: {
      title: 'Auction XI Terms of Use',
      description: 'Auction XI terms covering fictional gameplay, local saves, optional purchases, refunds and support.',
      body: `${heading('Auction XI Terms of Use')}<article>
      <section><h2>Agreement and publisher</h2><p>These terms govern your use of Auction XI, provided by Sunlight. See our <a href="/publisher/">Publisher Information</a> for the legal operator and ${link('privacy', 'Privacy Policy')} for data handling. If you do not agree, do not use the app. You must have the legal capacity or parent/guardian permission required where you live, and authorization from the payment account holder before purchasing.</p></section>
      <section><h2>Licence and fair use</h2><p>You receive a personal, non-exclusive licence to use the app for entertainment, subject to these terms and applicable store terms. Do not manipulate billing, distribute unauthorized copies, exploit security flaws or infringe others' rights. Restrictions do not remove rights expressly protected by law.</p><p>Teams, players, competitions and game finances are fictional. In-game auctions and rewards are simulation mechanics, not real-money betting, investments or cash prizes.</p></section>
      <section><h2>Careers and game balance</h2><p>Careers are stored locally. Purchases do not provide cloud backups. Removing app data, deleting a career or losing a device may permanently remove progress. Player development, match outcomes and league success are not guaranteed by purchases. Club debt, relegation, player retirement and the end of a managerial career can occur under the game rules.</p></section>
      <section><h2>Optional purchases and virtual currency</h2><p>Only products shown as available at checkout can be purchased. The store displays the actual localized price and any applicable tax before you confirm. Current product types are one-time purchases: virtual club funds, Remove Ads, extra career slots and commentary voices. Availability can vary by build and region; coin checkout is not enabled in the current testing build.</p><p>Virtual coins and club funds have no cash value, are not transferable outside the game and cannot be redeemed for money. Currency is applied once to the selected career when a verified purchase is fulfilled; it is not a reusable grant for every new career. Deleting or ending that career does not create a new grant.</p><p>Restore Purchases checks eligible permanent entitlements through the original store account. It does not restore local careers or reissue consumed currency. A refunded or revoked purchase may lose its entitlement. Where purchased currency is reversed, the corresponding game balance may be deducted, including becoming negative if those funds were spent. This does not create a real-money debt or require another purchase.</p></section>
      <section><h2>Refunds and purchase problems</h2><p>Google Play's billing and refund process and applicable consumer law govern purchase refunds. Contact ${link('support', 'support')} if an item is missing or a purchase fails. Do not repeatedly buy an undelivered item while the original order is pending. Nothing here excludes statutory refund rights or other mandatory consumer protections.</p></section>
      <section><h2>Updates, availability and intellectual property</h2><p>We may update features and balance or restrict access to address fraud, security threats or legal requirements. We will provide notice of material changes where required and respect applicable rights concerning paid content. Online store and advertising services depend on third parties and may be unavailable. The app's code, artwork and audio are protected by intellectual-property law; no rights are transferred beyond the permitted use.</p></section>
      <section><h2>Liability and disputes</h2><p>We do not guarantee uninterrupted service or recovery of local-only saves. Any exclusion or limitation applies only to the extent permitted by law; nothing excludes liability or consumer rights that cannot legally be excluded. These terms are governed by Indian law, subject to mandatory protections where you live. Competent courts in Maharashtra, India have non-exclusive jurisdiction, without limiting competent consumer forums.</p></section>
      <section><h2>Contact and ending use</h2><p>You may stop using the app at any time. See ${link('delete-data', 'data-deletion guidance')} before removing local data. Contact us about these terms or a dispute:</p>${contact}</section></article>`,
    },
    support: {
      title: 'Auction XI Help & Support',
      description: 'Contact Sunlight for Auction XI gameplay, billing or privacy assistance.',
      body: `${heading('Auction XI Help & Support')}<article><section class="action-card"><h2>Contact us</h2><p>Email your app version, device model and a short description of the problem. Screenshots help; hide personal information first.</p><p><a class="button" href="mailto:${email}?subject=Auction%20XI%20support">Email ${email}</a></p></section><section><h2>Purchase not showing?</h2><p>Use Restore Purchases in the Store for eligible permanent purchases, using the same Google Play account. Restoration does not reissue coins or recover a career. For an unresolved charge, send the product name, approximate date and non-secret Google Play order reference. Never send passwords, payment-card numbers or service credentials.</p><p><a href="https://support.google.com/googleplay/answer/2479637">Google Play refund guidance</a></p></section><section><h2>Lost save or privacy request?</h2><p>The current app uses local saves, not a Sunlight cloud account. Avoid clearing storage or reinstalling while troubleshooting; support cannot promise recovery of a deleted save. See ${link('delete-data', 'data-deletion instructions')} and the ${link('privacy', 'Privacy Policy')}.</p></section><section><h2>Publisher</h2>${contact}</section></article>`,
    },
    'delete-data': {
      title: 'Auction XI Data Deletion',
      description: 'How to delete Auction XI local careers and request deletion of support or purchase-service data.',
      body: `${heading('Auction XI Data Deletion')}<article><section><h2>Local saves are not an online account</h2><p>Auction XI currently has no Sunlight login or cloud-save account. Purchase services can still hold a pseudonymous customer record. Local deletion and a provider-data request are different actions.</p></section><section><h2>Delete a career in the app</h2><ol><li>Open the career you want to remove.</li><li>Go to Settings and choose Delete Career.</li><li>Read and confirm the permanent deletion warning.</li></ol><p>This removes the selected local career and its local backup, not other career slots or store purchase records.</p></section><section><h2>Remove all local app data</h2><p>In Android Settings, open Apps → Auction XI → Storage &amp; cache → Clear storage (wording varies by device). This permanently removes local careers and preferences. Review device/cloud backups separately through your Android or Google backup settings; clearing local data may not remove existing backup copies.</p></section><section class="action-card"><h2>Request deletion of data held by us</h2><p>Email us with the subject “Auction XI privacy deletion request”. Describe whether your request concerns support correspondence or a purchase-service record. For purchase-related records, provide an order reference if available; we will explain any verification needed. Never send passwords or full payment details.</p><p><a class="button" href="mailto:${email}?subject=Auction%20XI%20privacy%20deletion%20request">Request data deletion</a></p><p>We will review information under our control and coordinate relevant provider requests where possible. Records needed for legal obligations, fraud prevention or an unresolved dispute may be retained; we will explain applicable exceptions. Independently controlled Google Play records must be managed with Google. See the ${link('privacy', 'Privacy Policy')} for retention details.</p></section><section><h2>Purchases and refunds</h2><p>Deleting data is not a refund request. Permanent purchases may remain associated with your store account, but restoring them cannot recreate a deleted career or regrant consumed funds.</p>${contact}</section></article>`,
    },
  };
  return Object.fromEntries(Object.entries(pages).map(([slug, page]) => [
    `products/auction-xi/${slug ? slug + '/' : ''}index.html`,
    layout(config, { ...page, path: `${root}${slug ? slug + '/' : ''}` }),
  ]));
}
module.exports = { auctionPages };
