import type { StoryEvent, StoryTrigger, EffectSpec } from '../game/narrative';

type PressLine = readonly [string, string, StoryTrigger, string, string, string, string, string, string, string];

// Each line is one authored cricket question, not a combinatorial template.
// GOOD_MATCH and BAD_MATCH are based on personal rating, not the team's result.
const LINES: PressLine[] = [
  ['opening_partner', 'The Opening Stand', 'GOOD_MATCH', 'Your opening partner gave you a quiet word before the first ball. How much did that settle you?', 'Credit the partnership', 'I could play my game because we trusted each other.', 'Share the credit', 'They were part of every good decision out there.', 'Own the preparation', 'I was ready before I walked out. The partnership helped.'],
  ['strike_rotation', 'Runs Between the Big Shots', 'GOOD_MATCH', 'The boundary count was modest, but you kept the board moving. Was that the plan?', 'Value the singles', 'A quiet single kept the bowler from settling.', 'Control the tempo', 'You point to the score, not the highlight reel.', 'Promise more intent', 'You say there were still scoring balls you left behind.'],
  ['new_ball_patience', 'Surviving the New Ball', 'GOOD_MATCH', 'You left several tempting balls early. Did that patience change your innings?', 'Trust the leave', 'You explain why the first spell was worth respecting.', 'Praise the bowlers', 'The opposition earned your caution; the room notices.', 'Back your technique', 'You tell them you always knew the scoring window would open.'],
  ['middle_overs', 'The Middle Overs', 'GOOD_MATCH', 'The innings accelerated without a reckless shot. What did you read in the field?', 'Read the spaces', 'You describe the gaps instead of a miracle stroke.', 'Credit the runner', 'You recognise the partner who kept pace with you.', 'Keep the method private', 'You smile and leave next week’s opponents guessing.'],
  ['tail_support', 'Batting With the Tail', 'GOOD_MATCH', 'You managed the strike with the tail. How much did their nerve matter?', 'Praise the tail', 'The last pair hear their contribution recognised.', 'Explain the calls', 'You own the communication that protected both ends.', 'Focus on total', 'You keep the attention on the runs they added together.'],
  ['late_spell', 'The Late Spell', 'GOOD_MATCH', 'Your final spell was your sharpest. What changed after the earlier overs?', 'Trust the rhythm', 'You speak about finding a repeatable release point.', 'Credit the captain', 'The field and timing of the call get their due.', 'Stay guarded', 'You prefer not to explain a method the next side might study.'],
  ['slower_ball', 'The Change of Pace', 'GOOD_MATCH', 'The slower ball did its job today. Was that a planned variation?', 'Explain the setup', 'You describe the earlier deliveries that made it work.', 'Credit the wicketkeeper', 'You praise the signal and the catch behind the stumps.', 'Keep it hidden', 'You leave the exact grip out of the transcript.'],
  ['fielding_pressure', 'Saved Runs Matter', 'GOOD_MATCH', 'Two stops in the ring kept pressure on. Do fielding efforts get enough credit?', 'Praise the unit', 'You put the whole ring in the headline.', 'Own the standard', 'You say every saved run was worth the dive.', 'Ask for consistency', 'You admit the side still has cleaner work to do.'],
  ['catch_under_lights', 'Under the High Ball', 'GOOD_MATCH', 'You held a difficult chance under the lights. What was going through your mind?', 'Stay technical', 'You explain the footwork and keep the moment simple.', 'Praise the bowler', 'You say the chance began with the delivery.', 'Enjoy it', 'You let yourself smile; the work was worth celebrating.'],
  ['partner_turnaround', 'The Calm Between Wickets', 'GOOD_MATCH', 'The innings steadied after a wobble. What did you say to your partner?', 'Keep it simple', 'You describe the next ball, not a grand rescue.', 'Give them credit', 'You make the partner the centre of the recovery.', 'Own the responsibility', 'You admit someone had to take control.'],
  ['pressure_chase', 'A Chase With Patience', 'GOOD_MATCH', 'The target felt louder than the scoreboard. How did you keep your decisions clear?', 'Watch the ball', 'Your answer brings it back to one delivery at a time.', 'Trust the order', 'You name the depth of the batting group.', 'Embrace the noise', 'You say pressure is part of why you play.'],
  ['boundary_field', 'Finding the Gap', 'GOOD_MATCH', 'They changed the boundary field twice and you still found runs. What did you notice?', 'Discuss placement', 'You talk about manipulating the field, not overpowering it.', 'Praise the analyst', 'You acknowledge the preparation behind the read.', 'Save the detail', 'You do not give the next opponent a free scouting report.'],
  ['bowling_control', 'Dot-Ball Pressure', 'GOOD_MATCH', 'You did not take every wicket, but the run rate stalled in your overs. Is that enough?', 'Value control', 'You defend the unseen work of building pressure.', 'Credit the partner', 'You say wickets at the other end began with the squeeze.', 'Demand wickets', 'You welcome the spell but want a sharper finish.'],
  ['allround_balance', 'Two Ways Into the Match', 'GOOD_MATCH', 'You contributed in both disciplines. Which part mattered more today?', 'Back the balance', 'You say the team needed both contributions.', 'Pick the difficult job', 'You point to the skill that took most adjustment.', 'Credit the field', 'You shift attention to the work around you.'],
  ['debutant_help', 'A Word for the Debutant', 'GOOD_MATCH', 'A new teammate looked nervous beside you. Did you take time to help?', 'Make room for them', 'You say the dressing room has to make first days easier.', 'Praise their courage', 'You insist they earned their own place.', 'Keep it private', 'You leave a small dressing-room conversation there.'],
  ['home_support', 'The Home Ground', 'GOOD_MATCH', 'Did familiar surroundings change how you handled the contest?', 'Thank the crowd', 'You return the energy to those who came to watch.', 'Trust the routine', 'You say preparation travels to any ground.', 'Respect the visitors', 'You do not pretend home conditions win the match alone.'],
  ['away_silence', 'Quiet Away From Home', 'GOOD_MATCH', 'The ground was against you, yet your work stayed measured. Did the silence help?', 'Find focus', 'You describe concentrating on the next delivery.', 'Praise teammates', 'The small circle in the middle made the difference.', 'Enjoy the contest', 'You admit the away atmosphere sharpened you.'],
  ['selection_reward', 'Making the XI Count', 'GOOD_MATCH', 'You were trusted with this chance. What did you want the selectors to see?', 'Show reliability', 'You talk about doing the assigned job well.', 'Keep selection separate', 'You refuse to make one innings a verdict.', 'Ask for more', 'You say you are ready for a longer run.'],
  ['captain_trust', 'The Captain’s Call', 'GOOD_MATCH', 'The captain changed your role today and it worked. How quickly did you adapt?', 'Credit the call', 'You recognise the captain’s reading of the game.', 'Trust your range', 'You say your preparation covered more than one role.', 'Thank the group', 'You make adaptation sound like shared work.'],
  ['practice_payoff', 'Hours in the Nets', 'GOOD_MATCH', 'A shot you have been practising appeared at the right moment. Does the work feel vindicated?', 'Credit the coaches', 'You give the nets and their patient staff their due.', 'Stay cautious', 'One good execution is a start, not proof of mastery.', 'Enjoy the payoff', 'You allow yourself to say the hours mattered.'],
  ['wicketkeeper_call', 'A Voice From Behind', 'GOOD_MATCH', 'The keeper helped you adjust the field. How much did that conversation matter?', 'Credit the keeper', 'You call it a shared wicket, not a solo trick.', 'Explain the adjustment', 'You give a little detail about the changed line.', 'Keep the plan inside', 'You keep the pair’s signal between them.'],
  ['powerplay_intent', 'The First Six Overs', 'GOOD_MATCH', 'You found a scoring option during the early field restrictions. Was that a calculated risk?', 'Explain the field', 'You make the risk sound deliberate and grounded.', 'Praise the partner', 'You say the running made the boundary possible.', 'Back the instinct', 'You say sometimes a player has to take the opening.'],
  ['old_ball_work', 'When the Ball Softened', 'GOOD_MATCH', 'The old ball offered little. How did you stay useful in that phase?', 'Change the pace', 'You describe patience and a different length.', 'Trust the field', 'You give the close fielders credit for the pressure.', 'Keep learning', 'You admit the phase still tests you.'],
  ['tired_finish', 'Finishing on Empty', 'GOOD_MATCH', 'You looked tired near the end but kept contributing. What kept you going?', 'Name the team', 'You say teammates carried the hard moments together.', 'Trust the work', 'You point to conditioning done far from the cameras.', 'Admit the cost', 'You will recover properly before asking for more.'],
  ['quiet_contribution', 'Beyond the Headline', 'GOOD_MATCH', 'Your figures are not the obvious headline. What contribution are you proudest of?', 'Name the small moment', 'You choose a piece of cricket others nearly missed.', 'Praise the unit', 'You say the result was built by several hands.', 'Let it speak', 'You leave the performance to the scorebook.'],
  ['early_edge', 'The Early Chance', 'BAD_MATCH', 'An early chance went against you. Did it change the way you played?', 'Own the response', 'You accept the moment without blaming the surface.', 'Reset the routine', 'You say the next ball deserved a clearer mind.', 'Credit the opposition', 'You acknowledge they made the chance count.'],
  ['slow_start', 'A Slow Start', 'BAD_MATCH', 'You struggled to get moving. Did caution become a trap?', 'Admit it', 'You concede that safe cricket can still be poor cricket.', 'Defend the plan', 'You explain why the conditions demanded patience.', 'Ask for work', 'You want another net session before the next fixture.'],
  ['missed_yorker', 'The Yorker That Missed', 'BAD_MATCH', 'A planned yorker became a scoring ball. Was execution or choice the issue?', 'Own execution', 'You say the field deserved a better delivery.', 'Review the plan', 'You will reconsider when to use the option.', 'Credit the batter', 'You give the batter the read they earned.'],
  ['dropped_catch', 'The Catch That Went Down', 'BAD_MATCH', 'A catch did not stick. How do you keep it from following you?', 'Face the replay', 'You will work through the mechanics, not hide from them.', 'Move on quickly', 'You say the next chance cannot pay for the last.', 'Credit the team', 'You thank teammates who kept the pressure on.'],
  ['runout_mixup', 'The Mixed Call', 'BAD_MATCH', 'A running call went wrong. Where does the responsibility sit?', 'Take your share', 'You own your part of the confusion.', 'Protect the partner', 'You keep the private conversation in the dressing room.', 'Fix the signal', 'You promise a clearer call next time.'],
  ['expensive_over', 'A Costly Over', 'BAD_MATCH', 'One over changed your figures. How will you judge the spell as a whole?', 'Own the over', 'You do not use earlier balls as an excuse.', 'Look at the pattern', 'You will study where the line drifted.', 'Stay available', 'You tell the captain you still want the next over.'],
  ['short_ball_trap', 'The Short-Ball Trap', 'BAD_MATCH', 'They tested you with the short ball. Was your response too predictable?', 'Seek technical help', 'You plan to work on the shot with the coaches.', 'Pick the better ball', 'You say leaving was an option you ignored.', 'Back your method', 'You still believe your scoring stroke has a place.'],
  ['spin_stalemate', 'Held by Spin', 'BAD_MATCH', 'The spinner slowed your scoring. What would you change if you faced the spell again?', 'Use your feet', 'You talk about changing the bowler’s length.', 'Rotate earlier', 'You would take the easy single before the trap closes.', 'Study the release', 'You want a clearer read before offering a shot.'],
  ['pressure_field', 'The Ring Closed In', 'BAD_MATCH', 'Close fielders made every dot ball feel heavier. Did that hurry you?', 'Admit the pressure', 'You acknowledge the field affected your tempo.', 'Trust a reset', 'You want to rebuild the innings ball by ball.', 'Credit the captain', 'You say their placement deserves recognition.'],
  ['death_over_plan', 'At the Death', 'BAD_MATCH', 'Your late-overs plan came apart. Which part needs the most work?', 'Tighten execution', 'You commit to repeating the hard delivery in training.', 'Vary the plan', 'You need another answer when the first option fails.', 'Own the call', 'You accept the responsibility for your field and length.'],
  ['fielding_misread', 'A Ball in the Deep', 'BAD_MATCH', 'You misread the bounce in the deep. What did you learn from it?', 'Adjust position', 'You will change your starting spot next time.', 'Own the error', 'You make no excuse about lights or outfield.', 'Trust teammates', 'You appreciate the backup that limited the damage.'],
  ['partner_left', 'After a Wicket', 'BAD_MATCH', 'Your partner fell and your tempo changed. Did you try to do too much?', 'Slow down', 'You say the new pair needed one simple over.', 'Stay positive', 'You would rather keep looking for runs.', 'Share the plan', 'You will communicate better with the next batter.'],
  ['selection_noise', 'Noise Around Selection', 'BAD_MATCH', 'There is talk about your place. Can you keep selection out of the next innings?', 'Focus on process', 'You refuse to bat against a headline.', 'Welcome competition', 'You say a strong squad should challenge everyone.', 'Ask for clarity', 'You want an honest conversation with the coaches.'],
  ['training_load', 'Heavy Legs', 'BAD_MATCH', 'Your movement looked heavy. Is the workload catching up with you?', 'Speak to staff', 'You plan a measured conversation about recovery.', 'Own the fitness', 'You accept that preparation is part of the job.', 'Trust the schedule', 'You say one difficult outing is not the whole picture.'],
  ['bad_call', 'A Decision to Review', 'BAD_MATCH', 'A close decision left you frustrated. How do you talk about it now?', 'Respect the call', 'You keep the focus on the cricket still in your control.', 'Admit frustration', 'You are honest without attacking the officials.', 'Learn the moment', 'You want a calmer response if it happens again.'],
  ['lost_line', 'Searching for Line', 'BAD_MATCH', 'Your line wandered in the middle spell. What caused it?', 'Return to basics', 'You will repeat the release point in the nets.', 'Review the field', 'You want to align the plan with the protection.', 'Credit the batters', 'They forced you away from your preferred area.'],
  ['boundary_misfield', 'The Extra Boundary', 'BAD_MATCH', 'A misfield turned a single into more. How does the group respond?', 'Set the standard', 'You take the mistake into the next fielding session.', 'Protect the player', 'You refuse to isolate one teammate publicly.', 'Reset together', 'You say the next ball was the only useful answer.'],
  ['too_many_dots', 'Dots on the Board', 'BAD_MATCH', 'The dot balls piled up before you tried a release shot. What was missing?', 'Seek the single', 'You plan to find a safer scoring route earlier.', 'Back the shot', 'You say intent was right even if execution was not.', 'Read the field', 'You need to spot the gap before it disappears.'],
  ['bowling_partner', 'The Other End', 'BAD_MATCH', 'Your bowling partner carried the pressure today. Did you let them down?', 'Give them credit', 'You recognise their control without excusing yours.', 'Take responsibility', 'You say partnerships work only when both ends contribute.', 'Work on balance', 'You will compare plans before the next spell.'],
  ['captain_feedback', 'A Hard Conversation', 'BAD_MATCH', 'The captain spoke to you after the game. What did you take from it?', 'Listen first', 'You accept that direct feedback is useful.', 'Explain your plan', 'You share why you made the choice, then listen.', 'Take it to training', 'You want the next session to answer the criticism.'],
  ['away_conditions', 'Learning the Surface', 'BAD_MATCH', 'The surface played differently than you expected. Did you adapt soon enough?', 'Admit the delay', 'You say the adjustment should have come earlier.', 'Study the ground', 'You want a better read before the next visit.', 'Praise opposition', 'They understood the conditions faster.'],
  ['missed_stumping', 'A Half-Chance', 'BAD_MATCH', 'A stumping chance was difficult but available. How will you judge it?', 'Own the technique', 'You will review your footwork and take.', 'Keep perspective', 'You say one half-chance cannot define the whole spell.', 'Credit the bowler', 'You remember the ball that created it.'],
  ['final_over_nerves', 'Last-Over Nerves', 'BAD_MATCH', 'The final over demanded a clear plan. Did the occasion get to you?', 'Admit the nerves', 'You are honest about the pressure and its lesson.', 'Back the plan', 'You say the choice was sound, the execution short.', 'Ask for another chance', 'You want to be trusted in that moment again.'],
  ['form_question', 'A Run of Quiet Scores', 'BAD_MATCH', 'A few quiet scores have become a question. What is your answer?', 'Work with analyst', 'You want evidence before changing your game.', 'Trust your routine', 'You say the next innings is not a referendum.', 'Seek fresh eyes', 'You plan a technical conversation with a coach.'],
  ['recovery_choice', 'The Day After', 'BAD_MATCH', 'Would another net session help, or does your body need a quieter day?', 'Choose recovery', 'You give the body the rest the schedule allows.', 'Choose technique', 'You want a short, focused session, not punishment.', 'Ask the staff', 'You will take a second opinion before deciding.'],
];

const PLAYER_TRADE_OFFS: readonly (readonly [EffectSpec, EffectSpec])[] = [
  [{ integrity: 2, morale: 2 }, { confidence: 2, brand: 2 }],
  [{ relationship: [{ id: 'captain', delta: 3 }], morale: 2 }, { confidence: 3, integrity: -1 }],
  [{ relationship: [{ id: 'coach', delta: 3 }], form: 1 }, { brand: 2, confidence: 2 }],
  [{ integrity: 3, relationship: [{ id: 'mentor', delta: 2 }] }, { confidence: 3, morale: 1 }],
  [{ morale: 3, relationship: [{ id: 'captain', delta: 2 }] }, { form: 2, confidence: 1 }],
];

export const PLAYER_PRESS_SCENARIOS: StoryEvent[] = LINES.map((line, index) => {
  const [id, title, trigger, question, firstLabel, firstResult, secondLabel, secondResult, thirdLabel, thirdResult] = line;
  const [firstEffects, secondEffects] = PLAYER_TRADE_OFFS[index % PLAYER_TRADE_OFFS.length];
  return {
    id: `press_player_${id}`,
    title,
    trigger,
    speaker: 'Press Room',
    weight: 1,
    body: question,
    choices: [
      { id: 'first', label: firstLabel, effects: firstEffects, resultText: firstResult },
      { id: 'second', label: secondLabel, effects: secondEffects, resultText: secondResult },
      { id: 'third', label: thirdLabel, effects: { ...firstEffects, ...secondEffects, brand: 1 }, resultText: thirdResult },
    ],
  };
});
