import { z } from 'zod';

/** Zod schema so seed content is validated at load time (E3.1 DoD). */
export const TeamBlueprintSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  shortName: z.string().min(2).max(4),
  country: z.string().min(1),
  primaryColor: z.string().regex(/^#[0-9a-fA-F]{6}$/),
  secondaryColor: z.string().regex(/^#[0-9a-fA-F]{6}$/),
  strength: z.number().min(1).max(100),
  /** Starting division: 1 = top flight, 2 = second tier, 3 = local division. */
  tier: z.union([z.literal(1), z.literal(2), z.literal(3)]),
});

export type TeamBlueprint = z.infer<typeof TeamBlueprintSchema>;

/**
 * Fully fictional franchises — no real league or club names.
 * Format: City + Nickname. Covers 19 major cricketing nations.
 * Division 1 = top flight (tier: 1), Division 2 = second tier (tier: 2).
 */
const RAW_BLUEPRINTS: TeamBlueprint[] = [
  // ---- INDIA ----
  {
    id: 'mumbai_sharks',
    name: 'Mumbai Sharks',
    shortName: 'MUS',
    country: 'india',
    primaryColor: '#0E7C86',
    secondaryColor: '#F2C14E',
    strength: 82,
    tier: 1,
  },
  {
    id: 'delhi_lions',
    name: 'Delhi Lions',
    shortName: 'DEL',
    country: 'india',
    primaryColor: '#0032A0',
    secondaryColor: '#FFD700',
    strength: 79,
    tier: 1,
  },
  {
    id: 'kolkata_knights',
    name: 'Kolkata Knights',
    shortName: 'KOL',
    country: 'india',
    primaryColor: '#3A1078',
    secondaryColor: '#FFC72C',
    strength: 78,
    tier: 1,
  },
  {
    id: 'bengaluru_blazers',
    name: 'Bengaluru Blazers',
    shortName: 'BLZ',
    country: 'india',
    primaryColor: '#CC0000',
    secondaryColor: '#FFD700',
    strength: 77,
    tier: 1,
  },
  {
    id: 'chennai_kings',
    name: 'Chennai Kings',
    shortName: 'CHK',
    country: 'india',
    primaryColor: '#F8A01C',
    secondaryColor: '#0066CC',
    strength: 77,
    tier: 1,
  },
  {
    id: 'hyderabad_hawks',
    name: 'Hyderabad Hawks',
    shortName: 'HYH',
    country: 'india',
    primaryColor: '#FF6200',
    secondaryColor: '#000000',
    strength: 74,
    tier: 1,
  },
  {
    id: 'delhi_thunderbolts',
    name: 'Delhi Thunderbolts',
    shortName: 'DTB',
    country: 'india',
    primaryColor: '#1B3F8A',
    secondaryColor: '#E8C400',
    strength: 68,
    tier: 2,
  },
  {
    id: 'mumbai_warriors',
    name: 'Mumbai Warriors',
    shortName: 'MUW',
    country: 'india',
    primaryColor: '#4A4E69',
    secondaryColor: '#C9ADA7',
    strength: 65,
    tier: 2,
  },
  {
    id: 'kolkata_tigers',
    name: 'Kolkata Tigers',
    shortName: 'KOT',
    country: 'india',
    primaryColor: '#1A1A2E',
    secondaryColor: '#E94560',
    strength: 63,
    tier: 2,
  },
  {
    id: 'bengaluru_rebels',
    name: 'Bengaluru Rebels',
    shortName: 'BNR',
    country: 'india',
    primaryColor: '#8B0000',
    secondaryColor: '#DAA520',
    strength: 61,
    tier: 2,
  },

  // ---- AUSTRALIA ----
  {
    id: 'sydney_strikers',
    name: 'Sydney Strikers',
    shortName: 'SYS',
    country: 'australia',
    primaryColor: '#00AEEF',
    secondaryColor: '#012169',
    strength: 80,
    tier: 1,
  },
  {
    id: 'melbourne_stars',
    name: 'Melbourne Stars',
    shortName: 'MLS',
    country: 'australia',
    primaryColor: '#1E7145',
    secondaryColor: '#FFD700',
    strength: 78,
    tier: 1,
  },
  {
    id: 'brisbane_heat',
    name: 'Brisbane Heat',
    shortName: 'BRH',
    country: 'australia',
    primaryColor: '#FF6600',
    secondaryColor: '#000000',
    strength: 75,
    tier: 1,
  },
  {
    id: 'perth_thunder',
    name: 'Perth Thunder',
    shortName: 'PET',
    country: 'australia',
    primaryColor: '#004C8F',
    secondaryColor: '#F0A500',
    strength: 73,
    tier: 1,
  },
  {
    id: 'adelaide_blazers',
    name: 'Adelaide Blazers',
    shortName: 'ADB',
    country: 'australia',
    primaryColor: '#CC0000',
    secondaryColor: '#003366',
    strength: 71,
    tier: 1,
  },
  {
    id: 'melbourne_thunder',
    name: 'Melbourne Thunder',
    shortName: 'MLT',
    country: 'australia',
    primaryColor: '#22223B',
    secondaryColor: '#F2E9E4',
    strength: 65,
    tier: 2,
  },
  {
    id: 'sydney_sixers',
    name: 'Sydney Sixers',
    shortName: 'SXR',
    country: 'australia',
    primaryColor: '#CC1224',
    secondaryColor: '#FFFFFF',
    strength: 63,
    tier: 2,
  },
  {
    id: 'brisbane_bulls',
    name: 'Brisbane Bulls',
    shortName: 'BRB',
    country: 'australia',
    primaryColor: '#5E2750',
    secondaryColor: '#F5A623',
    strength: 60,
    tier: 2,
  },

  // ---- ENGLAND ----
  {
    id: 'london_foxes',
    name: 'London Foxes',
    shortName: 'LDF',
    country: 'england',
    primaryColor: '#0033A0',
    secondaryColor: '#CF142B',
    strength: 80,
    tier: 1,
  },
  {
    id: 'manchester_tigers',
    name: 'Manchester Tigers',
    shortName: 'MCT',
    country: 'england',
    primaryColor: '#DD0000',
    secondaryColor: '#FFFFFF',
    strength: 76,
    tier: 1,
  },
  {
    id: 'birmingham_bears',
    name: 'Birmingham Bears',
    shortName: 'BIB',
    country: 'england',
    primaryColor: '#003399',
    secondaryColor: '#F0A500',
    strength: 74,
    tier: 1,
  },
  {
    id: 'leeds_rhinos',
    name: 'Leeds Rhinos',
    shortName: 'LDR',
    country: 'england',
    primaryColor: '#1C4587',
    secondaryColor: '#FFFF00',
    strength: 72,
    tier: 1,
  },
  {
    id: 'nottingham_outlaws',
    name: 'Nottingham Outlaws',
    shortName: 'NTO',
    country: 'england',
    primaryColor: '#A01820',
    secondaryColor: '#FFD700',
    strength: 70,
    tier: 1,
  },
  {
    id: 'london_knights',
    name: 'London Knights',
    shortName: 'LDK',
    country: 'england',
    primaryColor: '#9E2A2B',
    secondaryColor: '#E9C46A',
    strength: 72,
    tier: 1,
  },
  {
    id: 'manchester_foxes',
    name: 'Manchester Foxes',
    shortName: 'MCF',
    country: 'england',
    primaryColor: '#BC4749',
    secondaryColor: '#F2E8CF',
    strength: 62,
    tier: 2,
  },
  {
    id: 'birmingham_wolves',
    name: 'Birmingham Wolves',
    shortName: 'BIW',
    country: 'england',
    primaryColor: '#6A0F49',
    secondaryColor: '#F7C948',
    strength: 60,
    tier: 2,
  },

  // ---- PAKISTAN ----
  {
    id: 'karachi_kings',
    name: 'Karachi Kings',
    shortName: 'KAK',
    country: 'pakistan',
    primaryColor: '#004B87',
    secondaryColor: '#FFD700',
    strength: 78,
    tier: 1,
  },
  {
    id: 'lahore_lions',
    name: 'Lahore Lions',
    shortName: 'LAL',
    country: 'pakistan',
    primaryColor: '#006400',
    secondaryColor: '#FFFFFF',
    strength: 76,
    tier: 1,
  },
  {
    id: 'islamabad_united',
    name: 'Islamabad United',
    shortName: 'ISU',
    country: 'pakistan',
    primaryColor: '#CC0000',
    secondaryColor: '#000000',
    strength: 74,
    tier: 1,
  },
  {
    id: 'multan_sultans',
    name: 'Multan Sultans',
    shortName: 'MUS2',
    country: 'pakistan',
    primaryColor: '#7B2D8B',
    secondaryColor: '#F5A623',
    strength: 71,
    tier: 1,
  },
  {
    id: 'faisalabad_falcons',
    name: 'Faisalabad Falcons',
    shortName: 'FAF',
    country: 'pakistan',
    primaryColor: '#B08D57',
    secondaryColor: '#264653',
    strength: 69,
    tier: 1,
  },
  {
    id: 'karachi_scorpions',
    name: 'Karachi Scorpions',
    shortName: 'KAS',
    country: 'pakistan',
    primaryColor: '#1D3557',
    secondaryColor: '#E63946',
    strength: 62,
    tier: 2,
  },
  {
    id: 'lahore_lions_2',
    name: 'Lahore Panthers',
    shortName: 'LPT',
    country: 'pakistan',
    primaryColor: '#2D6A4F',
    secondaryColor: '#FFFFFF',
    strength: 59,
    tier: 2,
  },

  // ---- SOUTH AFRICA ----
  {
    id: 'johannesburg_jaguars',
    name: 'Johannesburg Jaguars',
    shortName: 'JOJ',
    country: 'south_africa',
    primaryColor: '#FFD700',
    secondaryColor: '#007A33',
    strength: 78,
    tier: 1,
  },
  {
    id: 'cape_town_cobras',
    name: 'Cape Town Cobras',
    shortName: 'CTC',
    country: 'south_africa',
    primaryColor: '#0032A0',
    secondaryColor: '#FFFFFF',
    strength: 76,
    tier: 1,
  },
  {
    id: 'durban_dolphins',
    name: 'Durban Dolphins',
    shortName: 'DUR',
    country: 'south_africa',
    primaryColor: '#00B4D8',
    secondaryColor: '#03045E',
    strength: 74,
    tier: 1,
  },
  {
    id: 'pretoria_capitals',
    name: 'Pretoria Capitals',
    shortName: 'PRC',
    country: 'south_africa',
    primaryColor: '#2A9D8F',
    secondaryColor: '#1B1B1E',
    strength: 72,
    tier: 1,
  },
  {
    id: 'joburg_titans',
    name: 'Joburg Titans',
    shortName: 'JOT',
    country: 'south_africa',
    primaryColor: '#5C0099',
    secondaryColor: '#FFD700',
    strength: 70,
    tier: 1,
  },
  {
    id: 'valley_vipers',
    name: 'Valley Vipers',
    shortName: 'VAV',
    country: 'south_africa',
    primaryColor: '#386641',
    secondaryColor: '#A7C957',
    strength: 62,
    tier: 2,
  },
  {
    id: 'pretoria_bulls',
    name: 'Pretoria Bulls',
    shortName: 'PRB',
    country: 'south_africa',
    primaryColor: '#003399',
    secondaryColor: '#FFFF00',
    strength: 59,
    tier: 2,
  },

  // ---- NEW ZEALAND ----
  {
    id: 'auckland_aces',
    name: 'Auckland Aces',
    shortName: 'AKA',
    country: 'new_zealand',
    primaryColor: '#0033A0',
    secondaryColor: '#FFFFFF',
    strength: 76,
    tier: 1,
  },
  {
    id: 'wellington_firebirds',
    name: 'Wellington Firebirds',
    shortName: 'WEF',
    country: 'new_zealand',
    primaryColor: '#CC0000',
    secondaryColor: '#FFFFFF',
    strength: 74,
    tier: 1,
  },
  {
    id: 'christchurch_wizards',
    name: 'Christchurch Wizards',
    shortName: 'CHW',
    country: 'new_zealand',
    primaryColor: '#000080',
    secondaryColor: '#FFD700',
    strength: 72,
    tier: 1,
  },
  {
    id: 'hamilton_heroes',
    name: 'Hamilton Heroes',
    shortName: 'HAM',
    country: 'new_zealand',
    primaryColor: '#3D5A80',
    secondaryColor: '#98C1D9',
    strength: 70,
    tier: 1,
  },
  {
    id: 'auckland_falcons',
    name: 'Auckland Falcons',
    shortName: 'AKF',
    country: 'new_zealand',
    primaryColor: '#1A535C',
    secondaryColor: '#F7FFF7',
    strength: 64,
    tier: 2,
  },
  {
    id: 'wellington_giants',
    name: 'Wellington Giants',
    shortName: 'WEG',
    country: 'new_zealand',
    primaryColor: '#457B9D',
    secondaryColor: '#A8DADC',
    strength: 60,
    tier: 2,
  },

  // ---- SRI LANKA ----
  {
    id: 'colombo_lions',
    name: 'Colombo Lions',
    shortName: 'COL',
    country: 'sri_lanka',
    primaryColor: '#8B0000',
    secondaryColor: '#FFD700',
    strength: 74,
    tier: 1,
  },
  {
    id: 'galle_guardians',
    name: 'Galle Guardians',
    shortName: 'GAL',
    country: 'sri_lanka',
    primaryColor: '#0A3055',
    secondaryColor: '#F1A208',
    strength: 72,
    tier: 1,
  },
  {
    id: 'kandy_tuskers',
    name: 'Kandy Tuskers',
    shortName: 'KAN',
    country: 'sri_lanka',
    primaryColor: '#E76F51',
    secondaryColor: '#264653',
    strength: 70,
    tier: 1,
  },
  {
    id: 'colombo_strikers',
    name: 'Colombo Strikers',
    shortName: 'COS',
    country: 'sri_lanka',
    primaryColor: '#2F6690',
    secondaryColor: '#D9DCD6',
    strength: 62,
    tier: 2,
  },
  {
    id: 'kandy_warriors',
    name: 'Kandy Warriors',
    shortName: 'KAW',
    country: 'sri_lanka',
    primaryColor: '#006B35',
    secondaryColor: '#FFD700',
    strength: 58,
    tier: 2,
  },

  // ---- WEST INDIES ----
  {
    id: 'bridgetown_royals',
    name: 'Bridgetown Royals',
    shortName: 'BRR',
    country: 'west_indies',
    primaryColor: '#6A4C93',
    secondaryColor: '#F4A261',
    strength: 72,
    tier: 1,
  },
  {
    id: 'kingston_kings',
    name: 'Kingston Kings',
    shortName: 'KIK',
    country: 'west_indies',
    primaryColor: '#007A33',
    secondaryColor: '#FFD700',
    strength: 70,
    tier: 1,
  },
  {
    id: 'port_of_spain_pirates',
    name: 'Port of Spain Pirates',
    shortName: 'PSP',
    country: 'west_indies',
    primaryColor: '#CC0000',
    secondaryColor: '#000000',
    strength: 68,
    tier: 1,
  },
  {
    id: 'georgetown_guyana',
    name: 'Georgetown Giants',
    shortName: 'GGG',
    country: 'west_indies',
    primaryColor: '#006400',
    secondaryColor: '#FFD700',
    strength: 65,
    tier: 1,
  },
  {
    id: 'bridgetown_barracudas',
    name: 'Bridgetown Barracudas',
    shortName: 'BRB2',
    country: 'west_indies',
    primaryColor: '#1A1A2E',
    secondaryColor: '#E94560',
    strength: 60,
    tier: 2,
  },

  // ---- BANGLADESH ----
  {
    id: 'dhaka_dynamites',
    name: 'Dhaka Dynamites',
    shortName: 'DHD',
    country: 'bangladesh',
    primaryColor: '#006A4E',
    secondaryColor: '#F42A41',
    strength: 68,
    tier: 1,
  },
  {
    id: 'chattogram_challengers',
    name: 'Chattogram Challengers',
    shortName: 'CHC',
    country: 'bangladesh',
    primaryColor: '#CC0000',
    secondaryColor: '#FFFFFF',
    strength: 65,
    tier: 1,
  },
  {
    id: 'dhaka_gladiators',
    name: 'Dhaka Gladiators',
    shortName: 'DHG',
    country: 'bangladesh',
    primaryColor: '#003087',
    secondaryColor: '#FFD700',
    strength: 63,
    tier: 1,
  },
  {
    id: 'khulna_tigers',
    name: 'Khulna Tigers',
    shortName: 'KHT',
    country: 'bangladesh',
    primaryColor: '#FF6B00',
    secondaryColor: '#002366',
    strength: 60,
    tier: 2,
  },

  // ---- AFGHANISTAN ----
  {
    id: 'kabul_eagles',
    name: 'Kabul Eagles',
    shortName: 'KAE',
    country: 'afghanistan',
    primaryColor: '#0066CC',
    secondaryColor: '#CC0000',
    strength: 66,
    tier: 1,
  },
  {
    id: 'kandahar_kings',
    name: 'Kandahar Kings',
    shortName: 'KDK',
    country: 'afghanistan',
    primaryColor: '#006400',
    secondaryColor: '#FFD700',
    strength: 63,
    tier: 1,
  },
  {
    id: 'kabul_wolves',
    name: 'Kabul Wolves',
    shortName: 'KAW2',
    country: 'afghanistan',
    primaryColor: '#4A4E69',
    secondaryColor: '#C9ADA7',
    strength: 58,
    tier: 2,
  },

  // ---- ZIMBABWE ----
  {
    id: 'harare_hunters',
    name: 'Harare Hunters',
    shortName: 'HAH',
    country: 'zimbabwe',
    primaryColor: '#007A33',
    secondaryColor: '#FFD700',
    strength: 58,
    tier: 1,
  },
  {
    id: 'bulawayo_brave',
    name: 'Bulawayo Brave',
    shortName: 'BUB',
    country: 'zimbabwe',
    primaryColor: '#CC0000',
    secondaryColor: '#FFFFFF',
    strength: 55,
    tier: 1,
  },
  {
    id: 'harare_eagles',
    name: 'Harare Eagles',
    shortName: 'HAE',
    country: 'zimbabwe',
    primaryColor: '#1E3A5F',
    secondaryColor: '#F0A500',
    strength: 50,
    tier: 2,
  },

  // ---- IRELAND ----
  {
    id: 'dublin_darts',
    name: 'Dublin Darts',
    shortName: 'DUB',
    country: 'ireland',
    primaryColor: '#169B62',
    secondaryColor: '#FF883E',
    strength: 56,
    tier: 1,
  },
  {
    id: 'belfast_storm',
    name: 'Belfast Storm',
    shortName: 'BEL',
    country: 'ireland',
    primaryColor: '#003399',
    secondaryColor: '#FFCC00',
    strength: 53,
    tier: 1,
  },
  {
    id: 'dublin_rovers',
    name: 'Dublin Rovers',
    shortName: 'DUR2',
    country: 'ireland',
    primaryColor: '#006600',
    secondaryColor: '#FFFFFF',
    strength: 48,
    tier: 2,
  },

  // ---- SCOTLAND ----
  {
    id: 'edinburgh_eagles',
    name: 'Edinburgh Eagles',
    shortName: 'EDE',
    country: 'scotland',
    primaryColor: '#004B87',
    secondaryColor: '#FFFFFF',
    strength: 50,
    tier: 1,
  },
  {
    id: 'glasgow_gallants',
    name: 'Glasgow Gallants',
    shortName: 'GLG2',
    country: 'scotland',
    primaryColor: '#1A3057',
    secondaryColor: '#C8AA6E',
    strength: 48,
    tier: 1,
  },
  {
    id: 'aberdeen_tigers',
    name: 'Aberdeen Tigers',
    shortName: 'ABT',
    country: 'scotland',
    primaryColor: '#CC0000',
    secondaryColor: '#FFD700',
    strength: 44,
    tier: 2,
  },

  // ---- NETHERLANDS ----
  {
    id: 'amsterdam_lions',
    name: 'Amsterdam Lions',
    shortName: 'AML',
    country: 'netherlands',
    primaryColor: '#FF6600',
    secondaryColor: '#003087',
    strength: 50,
    tier: 1,
  },
  {
    id: 'rotterdam_raptors',
    name: 'Rotterdam Raptors',
    shortName: 'ROT',
    country: 'netherlands',
    primaryColor: '#0033A0',
    secondaryColor: '#FFD700',
    strength: 47,
    tier: 1,
  },
  {
    id: 'amsterdam_wolves',
    name: 'Amsterdam Wolves',
    shortName: 'AMW',
    country: 'netherlands',
    primaryColor: '#4A0E0E',
    secondaryColor: '#D4AF37',
    strength: 43,
    tier: 2,
  },

  // ---- UAE ----
  {
    id: 'dubai_falcons',
    name: 'Dubai Falcons',
    shortName: 'DUF',
    country: 'uae',
    primaryColor: '#C7A84F',
    secondaryColor: '#003580',
    strength: 58,
    tier: 1,
  },
  {
    id: 'abu_dhabi_knights',
    name: 'Abu Dhabi Knights',
    shortName: 'ADK',
    country: 'uae',
    primaryColor: '#006C5B',
    secondaryColor: '#FFD700',
    strength: 56,
    tier: 1,
  },
  {
    id: 'sharjah_warriors',
    name: 'Sharjah Warriors',
    shortName: 'SHW',
    country: 'uae',
    primaryColor: '#8B0000',
    secondaryColor: '#FFFFFF',
    strength: 53,
    tier: 1,
  },
  {
    id: 'dubai_dragons',
    name: 'Dubai Dragons',
    shortName: 'DUD',
    country: 'uae',
    primaryColor: '#1A1A2E',
    secondaryColor: '#D4AF37',
    strength: 48,
    tier: 2,
  },

  // ---- USA ----
  {
    id: 'new_york_nycricket',
    name: 'New York Empire',
    shortName: 'NYE',
    country: 'usa',
    primaryColor: '#003399',
    secondaryColor: '#FF0000',
    strength: 55,
    tier: 1,
  },
  {
    id: 'dallas_mavericks',
    name: 'Dallas Mavericks',
    shortName: 'DAM',
    country: 'usa',
    primaryColor: '#003366',
    secondaryColor: '#00538C',
    strength: 52,
    tier: 1,
  },
  {
    id: 'los_angeles_angels',
    name: 'Los Angeles Angels',
    shortName: 'LAA',
    country: 'usa',
    primaryColor: '#BA0021',
    secondaryColor: '#862633',
    strength: 50,
    tier: 1,
  },
  {
    id: 'houston_rockets',
    name: 'Houston Rockets',
    shortName: 'HOR',
    country: 'usa',
    primaryColor: '#CE1141',
    secondaryColor: '#C4CED4',
    strength: 48,
    tier: 2,
  },

  // ---- NAMIBIA ----
  {
    id: 'windhoek_warriors',
    name: 'Windhoek Warriors',
    shortName: 'WIW',
    country: 'namibia',
    primaryColor: '#009900',
    secondaryColor: '#003366',
    strength: 44,
    tier: 1,
  },
  {
    id: 'walvis_bay_waves',
    name: 'Walvis Bay Waves',
    shortName: 'WAW',
    country: 'namibia',
    primaryColor: '#0047AB',
    secondaryColor: '#FFFFFF',
    strength: 40,
    tier: 2,
  },

  // ---- PAPUA NEW GUINEA ----
  {
    id: 'port_moresby_pngc',
    name: 'Port Moresby Predators',
    shortName: 'PMP',
    country: 'png',
    primaryColor: '#FF0000',
    secondaryColor: '#000000',
    strength: 42,
    tier: 1,
  },
  {
    id: 'lae_lagers',
    name: 'Lae Legends',
    shortName: 'LAE',
    country: 'png',
    primaryColor: '#FFD700',
    secondaryColor: '#006400',
    strength: 38,
    tier: 2,
  },
];

export const TEAM_BLUEPRINTS: TeamBlueprint[] = z.array(TeamBlueprintSchema).parse(RAW_BLUEPRINTS);
