/* global __dirname */
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const root = path.resolve(__dirname, '..');
const outFile = path.join(root, 'src', 'config', 'buildInfo.generated.ts');
const appJsonPath = path.join(root, 'app.json');

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function gitValue(args, fallback) {
  try {
    return execFileSync('git', args, { cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
  } catch {
    return fallback;
  }
}

function envName() {
  return process.env.EXPO_PUBLIC_APP_ENV || process.env.APP_ENV || process.env.NODE_ENV || 'development';
}

const app = readJson(appJsonPath).expo;
const commit = gitValue(['rev-parse', '--short=12', 'HEAD'], 'unknown-no-git');
const branch = gitValue(['branch', '--show-current'], 'unknown-no-git');
const dirty = gitValue(['status', '--short'], '');
const builtAt = new Date().toISOString();

const buildInfo = {
  appName: app.name,
  appVersion: app.version,
  androidVersionCode: app.android && app.android.versionCode != null ? String(app.android.versionCode) : 'unknown',
  iosBuildNumber: app.ios && app.ios.buildNumber ? String(app.ios.buildNumber) : 'unknown',
  gitCommit: commit,
  gitBranch: branch,
  gitDirty: dirty.length > 0,
  builtAt,
  environment: envName(),
  dataConfigVersion: process.env.EXPO_PUBLIC_DATA_CONFIG_VERSION || 'unversioned',
};

const contents = `// Generated by scripts/writeBuildInfo.js. Do not edit by hand.
export const GENERATED_BUILD_INFO = ${JSON.stringify(buildInfo, null, 2)} as const;
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, contents);
console.log(`Wrote ${path.relative(root, outFile)}`);
